[build]
	publish = "html/"
	functions = "functions/"
	command = "npm run prod"

[[headers]]
	for = "/*"

	[headers.values]
		X-Content-Type-Options = "nosniff"
		Content-Security-Policy = "frame-ancestors 'none';"
		X-Frame-Options = "DENY"
		X-XSS-Protection = "1; mode=block"
		Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
	for = "/rss"
	[headers.values]
		Content-Type = "text/xml"

[[headers]]
	for = "/api/beers.json"
	[headers.values]
		Content-Type = "application/json"

[[headers]]
	for = "/api/breweries.json"
	[headers.values]
		Content-Type = "application/json"
